#Wiersz Wisławy Szymborskiej "Wielkie to szczęście"

print("Wielkie to szczęście")
print("nie wiedzieć dokładnie,")
print("na jakim świecie się żyje.")
print("")
print("Trzeba by było")
print("istnieć bardzo długo,")
print("stanowczo dłużej")
print("niż istnieje on.")
print("")
print("Choćby dla porównania")
print("poznać inne światy.")
print("")
print("unieść się ponad ciało")
print("które niczego tak dobrze nie umie,")
print("jak ograniczać")
print("i stwarzać trudności.")
print("")
print("Dla dobra badań,")
print("jasności obrazu")
print("i ostatecznych wniosków")
print("wzbić się ponad czas,")
print("w którym to wszystko pędzi i wiruje.")
print("")
print("Z tej perspektywy")
print("żegnajcie na zawsze")
print("szczegóły i epizody.")
print("")
print("Liczenie dni tygodnia")
print("musiałoby się wydawać")
print("czynnością bez sensu,")
print("wrzucenie listu do skrzynki")
print("wybrykiem głupiej młodości,")
print("")
print("napis “Nie deptać trawy”")
print("napisem szalonym.")
print("")
print("(Koniec i początek, 1993)")
